In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

x = np.array([1, 2])
print(x.dtype)

x = np.array([1.0, 2.0])
print(x.dtype)

x = np.array([1, 2], dtype = np.int64)
print(x.dtype)

int64
float64
int64


In [ ]:
import numpy as np

arr1 = np.array([[4, 7], [2, 6]],
                 dtype = np.float64)

arr2 = np.array([[3, 6], [2, 8]],
                 dtype = np.float64)

Sum = np.add(arr1, arr2)
print(Sum)

Sum1 = np.sum(arr1)
print(Sum1)

Sqrt = np.sqrt(arr1)
print(Sqrt)

Trans_arr = arr1.T
print(Trans_arr)

[[ 7. 13.]
 [ 4. 14.]]
19.0
[[2.         2.64575131]
 [1.41421356 2.44948974]]
[[4. 2.]
 [7. 6.]]


In [ ]:
import numpy as np


array1 = np.array([1, 3, 5])
print("np.array():\n", array1)


array2 = np.zeros((3, 3))
print("\nnp.zeros():\n", array2)


array3 = np.ones((2, 4))
print("\nnp.ones():\n", array3)

np.array():
 [1 3 5]

np.zeros():
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

np.ones():
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np

# create a 1D array
array1 = np.array([1, 3, 5, 7, 9, 11])

# reshape the 1D array into a 2D array
array2 = np.reshape(array1, (2, 3))

# transpose the 2D array
array3 = np.transpose(array2)

print("Original array:\n", array1)
print("\nReshaped array:\n", array2)
print("\nTransposed array:\n", array3)

Original array:
 [ 1  3  5  7  9 11]

Reshaped array:
 [[ 1  3  5]
 [ 7  9 11]]

Transposed array:
 [[ 1  7]
 [ 3  9]
 [ 5 11]]


In [ ]:
Create an array
Zeroes
Ones
Create an empty array
Arrange function
Linespace
Imateix
Full function
Random value generation

SyntaxError: invalid syntax (2972550597.py, line 1)

In [ ]:
np.array([])

array([], dtype=float64)

In [ ]:
#arange function
a=np.arange(1,20)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
Conversion from 1d to 2d
Reshape
Transpose append
Delete
Split
Vstack
Hstack
Concatense
Shape,size,datatype

In [ ]:
import numpy as np
a = np.linspace(1, 5, num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [ ]:
import numpy as geek

a = geek.full([2, 5], 67, dtype = int)
print("\nMatrix a : \n", a)

c = geek.full([3, 3], 6)
print("\nMatrix c : \n", c)


Matrix a : 
 [[67 67 67 67 67]
 [67 67 67 67 67]]

Matrix c : 
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [ ]:
a= np.random.randint(100)

print(a)

31


In [ ]:
a = np.array([10,20,30,40,50,60,70])
r = np.delete(a, 0)
print (r)

[20 30 40 50 60 70]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 2)
print(newarr[0])
print(newarr[1])

[1 2 3]
[4 5 6]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result_1d = np.vstack((a, b))
print(result_1d)

[[1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result_1d = np.hstack((a, b))
print(result_1d)

[1 2 3 4 5 6]


In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])
res1d = np.concatenate((a, b))
print(res1d)

[1 2 3 4]


In [ ]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5, 6])
print(b)

[1 2 3 4 5 6]


In [ ]:
arr = np.array([1, 2, 3,4,5], dtype='int8')

print(f"Shape: {arr.shape}")
print(f"Size:  {arr.size}")
print(f"Dtype: {arr.dtype}")

Shape: (5,)
Size:  5
Dtype: int8


In [ ]:
'''
Create 2 arrays
Convert to 2d array
Row wise sum,column wise mean
'''

'\nCreate 2 arrays\nConvert to 2d array\nRow wise sum,column wise mean\n'

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1)
print(arr2)

[1 2 3]
[4 5 6]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
res = np.column_stack((arr1, arr2))
print(res)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
np.ndim(arr1)

1

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
row_sums = np.sum(arr, axis=1)

print(row_sums)

[ 6 15]


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
column_means = np.mean(arr, axis=0)
print(column_means)

[4. 5. 6.]


In [ ]:
np.ndim(arr)

2

In [ ]:
rng = np.random.default_rng()
#5 floats between 0and 1
a1=rng.random(6)
a2=rng.random(6)
print(a1)
print(a2)

[0.56684784 0.91332514 0.91159422 0.29549344 0.65994855 0.1007288 ]
[0.56947232 0.57781192 0.99295086 0.49691689 0.31817105 0.60729707]


In [ ]:
np.hstack((a1,a2))

array([0.56684784, 0.91332514, 0.91159422, 0.29549344, 0.65994855,
       0.1007288 , 0.56947232, 0.57781192, 0.99295086, 0.49691689,
       0.31817105, 0.60729707])

In [ ]:
np.vstack((a1,a2))

array([[0.56684784, 0.91332514, 0.91159422, 0.29549344, 0.65994855,
        0.1007288 ],
       [0.56947232, 0.57781192, 0.99295086, 0.49691689, 0.31817105,
        0.60729707]])

In [ ]:
ones=np.ones(2)
ones

array([1., 1.])

In [ ]:
unit=np.eye(3)
unit

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a + b)
print((a*b))

[11 22 33]
[10 40 90]


In [ ]:
Create two arrays using random function
Merge two of them
And remove duplicates

In [ ]:
# 1. Create an array of 5 random floating-point numbers between 0 and 1
float_array = np.random.rand(5)

# 2. Create an array of 5 random integers between 10 and 50
int_array = np.random.randint(10, 50, size=5)

print("Float Array:", float_array)
print("Integer Array:", int_array)
result = np.concatenate((float_array,int_array))
print(result)
unique_arr = np.unique(result)
print(unique_arr)

Float Array: [0.42463576 0.30293873 0.30804057 0.54091196 0.95846053]
Integer Array: [19 14 23 16 47]
[ 0.42463576  0.30293873  0.30804057  0.54091196  0.95846053 19.
 14.         23.         16.         47.        ]
[ 0.30293873  0.30804057  0.42463576  0.54091196  0.95846053 14.
 16.         19.         23.         47.        ]


In [ ]:
unique_arr

array([ 0.37245223,  0.71925867,  0.8027147 ,  0.82539542,  0.95109012,
       14.        , 18.        , 38.        , 40.        , 45.        ])

In [ ]:
Mean median mode
Minimum maximum
Sort
Copy function
View function
Array indexing,slicing

In [ ]:
original = np.array([1, 2, 3])
copied = original.copy()

# Modifying the copy does not change the original
copied[0] = 6
print(original)
print(copied)
arr=np.array([1, 2, 3, 4, 5])
v = arr.view()
# Modify an element in the view
v[0] = 10
# Both the original and the view show the change
print("Original:",arr)
print("View:", v)

[1 2 3]
[6 2 3]
Original: [10  2  3  4  5]
View: [10  2  3  4  5]


In [ ]:
#Indexing
arr = np.array([10, 20, 30, 40])
print(arr[0])
print(arr[3])

matrix = np.array([[1, 2], [3, 4]])
print(matrix[1, 0])

10
40
3


In [ ]:
#Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
arr = np.array([10, 25, 40, 55, 70])

# Find all elements greater than 30
result = arr[arr > 30]
print(result)

[40 55 70]


In [ ]:
import pandas as pd
df1 = pd.DataFrame({'id': [1, 2], 'name': ['Alice', 'Bob']})
df2 = pd.DataFrame({'id': [1, 2], 'salary': [50000, 60000]})

# Merging on the 'id' column
result = pd.merge(df1, df2, on='id')
print(result)
#concat
df_combined = pd.concat([df1, df2], axis=0)
print(df_combined)
print(j)

   id   name  salary
0   1  Alice   50000
1   2    Bob   60000
   id   name   salary
0   1  Alice      NaN
1   2    Bob      NaN
0   1    NaN  50000.0
1   2    NaN  60000.0
   id_left   name  id_right  salary
0        1  Alice         1   50000
1        2    Bob         2   60000


In [ ]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 32, 45, 35],
    'Salary': [50000, 80000, 120000, 95000]
})

# Filter: Age greater than 30
filtered_df = df[df['Age'] > 30]
print(filtered_df)

      Name  Age  Salary
1      Bob   32   80000
2  Charlie   45  120000
3    David   35   95000
